version: 2

sources:
  - name: staging
    database: de-zoomcamp-420207
    schema: uk_cycling

    tables:
      - name: cycleways_cycling_partitioned
      - name: central_cycling_partitioned
      - name: outer_cycling_partitioned
      - name: inner_cycling_partitioned
